### ISSUE TITLE
Show friendly error when inputting a Node ID into Shoggoth Explore

### ISSUE THREAD

**Issue by samsara3978** [shog-ai/shoggoth#20]
Both Node IDs and Profile IDs start with `SHOG`. User might find it confusing that inputting a Node ID into Explorer causes a "invalid Shoggoth ID" error.

Solution: output a more friendly error, e.g. "You've entered a Shoggoth Node ID (starts with SHOGN). Shoggoth Profile ID (starts with SHOG) is expected."

**Comment by thenetrunna** [comment]
obsoleted by v1.0.2
