### ISSUE TITLE
.clang-format for consistency/maintainability/reduced-friction

### ISSUE THREAD

**Issue by 0x5844** [shog-ai/shoggoth#21]
Hey!

On my trip through the codebase on VSCode, I realized the indentation style of K&R which wasn't part of my VSCode settings. This gave me an idea; it might be good to include `.clang-format` at this point, I believe it comes with several benefits out of the box:

1. **Consistency**: It enforces a consistent coding style across the entire codebase, which is important for readability and maintainability.
2. **Automation**: It automates the formatting process, saving time and reducing the mental overhead needed to manually format code according to a style guide (In my case it was a minor config adjustment but it grows)
3. **Reduced Friction**: It minimizes code review time spent on style issues.
4. **Editor/IDE Agnostic**: It works across different editors and IDEs that support clang-format. This is particularly useful in diverse development environments (such as my case).

I'm more than happy to discuss this further, let me know what you think. I think these little adjustments make the long run of open-source much smoother! 🥳

**Comment by thenetrunna** [comment]
obsoleted by v1.0.2
