### ISSUE TITLE
If a file is a PDF, show it in a PDF.js viewer in browser

### ISSUE THREAD

**Issue by samsara3978** [shog-ai/shoggoth#32]
Currently PDFs are either displayed as "file too large" or as plain text of the PDF code: https://shoggoth.network/explorer/profile/SHOG0920d63a36a97ee8e3cc56f04b208267/papers/sample/sample.pdf

I think using something like https://mozilla.github.io/pdf.js/ would be nicer.

**Comment by thenetrunna** [comment]
obsoleted by v0.2.1
