### ISSUE TITLE
[INFO]: Waiting for db process to exit ...

### ISSUE THREAD

**Issue by vyomakesh09** [shog-ai/shoggoth#37]
Yo, we running Ubuntu and here's the neofetch o/p. we having an issue running the node that goes in a loop saying "[INFO]: Waiting for db process to exit ... "

```
v@v-System-Product-Name:~$ neofetch
            .-/+oossssoo+/-.               v@v-System-Product-Name 
        `:+ssssssssssssssssss+:`           ----------------------- 
      -+ssssssssssssssssssyyssss+-         OS: Ubuntu 22.04.3 LTS x86_64 
    .ossssssssssssssssssdMMMNysssso.       Kernel: 6.2.0-36-generic 
   /ssssssssssshdmmNNmmyNMMMMhssssss/      Uptime: 26 mins 
  +ssssssssshmydMMMMMMMNddddyssssssss+     Packages: 2293 (dpkg), 18 (snap) 
 /sssssssshNMMMyhhyyyyhmNMMMNhssssssss/    Shell: bash 5.1.16 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Resolution: 1920x1080 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   DE: GNOME 42.9 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM: Mutter 
ossyNMMMNyMMhsssssssssssssshmmmhssssssso   WM Theme: Adwaita 
+sssshhhyNMMNyssssssssssssyNMMMysssssss+   Theme: Yaru-red-dark [GTK2/3] 
.ssssssssdMMMNhsssssssssshNMMMdssssssss.   Icons: Yaru-red [GTK2/3] 
 /sssssssshNMMMyhhyyyyhdNMMMNhssssssss/    Terminal: gnome-terminal 
  +sssssssssdmydMMMMMMMMddddyssssssss+     CPU: 13th Gen Intel i7-13700K (24) @ 5.300GHz 
   /ssssssssssshdmNNNNmyNMMMMhssssss/      GPU: NVIDIA 01:00.0 NVIDIA Corporation Device 2704 
    .ossssssssssssssssssdMMMNysssso.       Memory: 6456MiB / 31825MiB 
      -+sssssssssssssssssyyyssss+-
        `:+ssssssssssssssssss+:`                                   
            .-/+oossssoo+/-.                                       

```

v@v-System-Product-Name:~/shoggoth/node$ shog node run 
[INFO]: Initializing node
[INFO]: Using default runtime path: /home/v/shoggoth
[INFO]: NODE VERSION: v0.1.5
[INFO]: NODE ID: SHOGN906a64403463eed272e5541449d0e67a
[INFO]: NODE HOST: 0.0.0.0
[INFO]: NODE PORT: 6969
[INFO]: NODE PUBLIC HOST: http://103.7.205.36:6969
[INFO]: DB HOST: 127.0.0.1
[INFO]: DB PORT: 6961

[INFO]: Starting node server
[INFO]: Explorer: http://0.0.0.0:6969/
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...
[INFO]: Waiting for db process to exit ...

**Comment by thenetrunna** [comment]
obsoleted by v1.0.2
