### ISSUE TITLE
Documentation makes no difference between Shoggoth and Torrents

### ISSUE THREAD

**Issue by surak** [shog-ai/shoggoth#52]
I mean, the obvious comparison here is with the torrents, right? 

How does shoggoth differentiates itself from it? What does it provide which torrent does not, and vice-versa?

I introduced the tool to my AI colleagues and the question literally everyone asks is: "so, torrent?"

It would be productive to see why this is not just another BitTorrent.

Thanks.

**Comment by thenetrunna** [comment]
obsoleted by v1.0.2
